using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    /// <summary>
    /// ViewModel and EF entity for obstacle data registration.
    /// Used to both display the form and store submitted reports in the database.
    /// 
    /// DESIGN NOTE: Draft reports are stored with Status = NotApproved (no admin comments).
    /// This conflates "draft" and "rejected" states but simplifies the status enum to 3 values.
    /// </summary>
    public class ObstacleData
    {
        /// <summary>
        /// Primary key for the database table.
        /// Auto-generated by the database on insert.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Name of the obstacle (e.g., "Windmill", "Power line", "Cell tower").
        /// Required field with maximum length of 100 characters.
        /// For missing obstacles, name should start with "MISSING - ".
        /// </summary>
        [Required, StringLength(100)]
        [DisplayName("Obstacle name")]
        public string ObstacleName { get; set; } = string.Empty;

        /// <summary>
<<<<<<< HEAD
        /// Height of the obstacle in meters.
        /// Must be between 0 and 1000 meters per aviation regulations.
        /// Nullable to allow drafts without complete information.
=======
        /// Foreign key to obstacle category.
>>>>>>> origin/Origin/main-final
        /// </summary>
        [Required]
        [DisplayName("Category")]
        public int CategoryId { get; set; }

        /// <summary>
        /// Navigation property to category.
        /// </summary>
        [ForeignKey("CategoryId")]
        public ObstacleCategory? Category { get; set; }
        /// <summary>
        /// Height of the obstacle in meters.
        /// Must be between 0 and 1000 meters per aviation regulations.
        /// Nullable to allow drafts without complete information.
        /// </summary>
        
        [Range(0, 1000, ErrorMessage = "Height must be between 0 and 1000 meters.")]
        [DisplayName("Height (m)")]
        public decimal? ObstacleHeight { get; set; }

        /// <summary>
        /// Description of the obstacle. Max 500 characters.
        /// Required field that provides context and details about the obstacle.
        /// </summary>
        [Required(ErrorMessage = "Description is required.")]
        [StringLength(500)]
        [DisplayName("Description")]
        [DataType(DataType.MultilineText)]
        public string? ObstacleDescription { get; set; }

        /// <summary>
        /// Latitude coordinate picked from map (WGS84 coordinate system).
        /// Optional field - can be null for draft reports.
        /// Uses decimal type for precision required by GeoJSON standard.
        /// </summary>
        [DisplayName("Latitude")]
        public decimal? Latitude { get; set; }

        /// <summary>
        /// Longitude coordinate picked from map (WGS84 coordinate system).
        /// Optional field - can be null for draft reports.
        /// Uses decimal type for precision required by GeoJSON standard.
        /// </summary>
        [DisplayName("Longitude")]
        public decimal? Longitude { get; set; }

        /// <summary>
        /// UTC timestamp when the report was submitted by the user.
        /// Updated each time the report is edited.
        /// </summary>
        [Required]
        [DisplayName("Reported at")]
        public DateTime ReportedAt { get; set; }

        /// <summary>
        /// UTC timestamp for when the obstacle was first registered in the system.
        /// Set automatically at object creation and never changed.
        /// Used for audit trail and sorting by original submission date.
        /// </summary>
        [Required]
        [DisplayName("Logged at")]
        public DateTime DateData { get; set; } = DateTime.UtcNow;

        // ===== USER TRACKING FIELDS =====
        // These fields cache user information for performance and audit purposes.
        // They avoid the need to join with AspNetUsers table for every query.

        /// <summary>
        /// Identity UserId of the reporter (foreign key to AspNetUsers table).
        /// Used for security checks and filtering reports by user.
        /// Max length 450 matches ASP.NET Identity's Id field length.
        /// </summary>
        [StringLength(450)]
        [DisplayName("Reported by (User ID)")]
        public string? ReportedByUserId { get; set; }

        /// <summary>
        /// Full name of the reporter (cached from ApplicationUser.FullName).
        /// Stored here for performance - avoids joining AspNetUsers for display.
        /// </summary>
        [StringLength(100)]
        [DisplayName("Reporter name")]
        public string? ReporterName { get; set; }

        /// <summary>
        /// Organization of the reporter (cached from ApplicationUser.Organization).
        /// Used for filtering reports by organization (e.g., "Norsk Luftambulanse").
        /// Enables organization-level report visibility without complex queries.
        /// </summary>
        [StringLength(100)]
        [DisplayName("Reporter organization")]
        public string? ReporterOrganization { get; set; }

        // ===== STATUS FIELD =====

        /// <summary>
        /// Current status of the report in the workflow.
        /// 
        /// Status meanings:
        /// - Pending (0): Report has been submitted and is awaiting admin review
        /// 
        /// - Approved (1): Report has been reviewed and approved by a Registry Administrator
        /// 
        /// - NotApproved (2): Either a draft not yet submitted, OR a report rejected by admin
        ///   - Draft: No AdminComments, no ReviewedByUserId, no LastReviewedAt
        ///   - Rejected: Has AdminComments from admin explaining why it was rejected
        /// 
        /// DESIGN NOTE: Using NotApproved for both drafts and rejections simplifies the enum
        /// but requires checking AdminComments to distinguish between the two states.
        /// This was a team design decision to keep only 3 status values.
        /// </summary>
        [Required]
        [DisplayName("Status")]
        public ReportStatus Status { get; set; } = ReportStatus.NotApproved;

        // ===== ADMIN WORKFLOW FIELDS =====
        // These fields support the admin review process and assignment workflow.

        /// <summary>
        /// UserId of the Registry Administrator assigned to review this report.
        /// Null if the report is unassigned.
        /// Allows workload distribution among multiple administrators.
        /// </summary>
        [StringLength(450)]
        [DisplayName("Assigned to (User ID)")]
        public string? AssignedToUserId { get; set; }

        /// <summary>
        /// Name of the Registry Administrator assigned to this report (cached).
        /// Stored here to avoid joining AspNetUsers when displaying assignment info.
        /// </summary>
        [StringLength(100)]
        [DisplayName("Assigned to")]
        public string? AssignedToName { get; set; }

        /// <summary>
        /// Admin comments/feedback about the report.
        /// 
        /// Usage:
        /// - Required when rejecting a report (Status = NotApproved with admin review)
        /// - Explains to the pilot why their report was rejected
        /// - Cleared when a report is approved
        /// - Null for draft reports (Status = NotApproved without admin review)
        /// 
        /// Max 1000 characters to provide sufficient detail for rejection reasons.
        /// </summary>
        [StringLength(1000)]
        [DisplayName("Admin comments")]
        [DataType(DataType.MultilineText)]
        public string? AdminComments { get; set; }

        /// <summary>
        /// UserId of the Registry Administrator who last reviewed/updated this report.
        /// Set when admin approves, rejects, or changes the status.
        /// Used for audit trail and accountability.
        /// </summary>
        [StringLength(450)]
        public string? ReviewedByUserId { get; set; }

        /// <summary>
        /// Name of the Registry Administrator who last reviewed this report (cached).
        /// Displayed to pilots so they know who processed their report.
        /// </summary>
        [StringLength(100)]
        [DisplayName("Reviewed by")]
        public string? ReviewedByName { get; set; }

        /// <summary>
        /// Timestamp of last status change by Registry Administrator.
        /// Null if the report has never been reviewed by an admin.
        /// Used to distinguish between draft (never reviewed) and rejected (reviewed).
        /// </summary>
        [DisplayName("Last reviewed at")]
        public DateTime? LastReviewedAt { get; set; }

        /// <summary>
        /// Helper property: Determines if this report is likely a draft (not yet submitted).
        /// 
        /// Logic: A report is considered a draft if:
        /// 1. Status is NotApproved (could be draft OR rejection)
        /// 2. AND AdminComments is empty (not a rejection with feedback)
        /// 3. AND LastReviewedAt is null (never been reviewed by an admin)
        /// 
        /// This heuristic is needed because drafts and rejections share the same status.
        /// Used in UI to show "Draft" badge vs "Rejected" badge.
        /// 
        /// LIMITATION: If an admin manually sets Status to NotApproved without adding comments,
        /// it will appear as a draft. This is a known limitation of the current design.
        /// </summary>
        public bool IsProbablyDraft =>
            Status == ReportStatus.NotApproved &&
            string.IsNullOrEmpty(AdminComments) &&
            !LastReviewedAt.HasValue;
    }

    /// <summary>
    /// Enum defining the possible states of a report.
    /// 
    /// DESIGN NOTE: Only 3 status values as per team decision.
    /// Draft state is implicit (NotApproved + no admin comments).
    /// 
    /// Status flow:
    /// NotApproved (draft) → Pending → Approved
    ///                              ↓
    ///                         NotApproved (rejected)
    /// </summary>
    public enum ReportStatus
    {
        /// <summary>
        /// Pending (0): Report has been submitted for review.
        /// Awaiting action by a Registry Administrator.
        /// This is the only status that admins actively process.
        /// </summary>
        Pending = 0,

        /// <summary>
        /// Approved (1): Report has been reviewed and approved by Registry Administrator.
        /// Ready to be integrated into the National Aviation Obstacle Register (NRL).
        /// Admin comments are cleared when approving.
        /// </summary>
        Approved = 1,

        /// <summary>
        /// NotApproved (2): Report is either:
        /// - A draft not yet submitted (no admin comments, no review date)
        /// - Rejected by admin with feedback (has admin comments and review date)
        /// 
        /// Use IsProbablyDraft property to distinguish between these cases.
        /// </summary>
        NotApproved = 2
    }
}
